name: hello_dbt
version: "1.0.0"
config-version: 2
profile: hello_dbt

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  hello_dbt:
    +materialized: view
